GET http://hillel-php.laravel/api/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer 9|B5Jlh7lYT9HU0FaOybb9SkZRCo6LNeiQJqoCA0bI
#Authorization: Bearer 10|NbmU5DzUuK0me7ib1Mvpl2RKEq1qPDb03EKXmord

###

POST http://hillel-php.laravel/api/token/create
Accept: application/json
Content-Type: application/json

{
  "email": "cortney75@example.org",
  "password": "password",
  "device_name": "phone"
}

###
#
GET http://hillel-php.laravel/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 4|8Cgn7j59kRxLsOIIdG4RlptvQ2l6suNpZUO1bgYS

###

GET http://hillel-php.laravel/api/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 4|8Cgn7j59kRxLsOIIdG4RlptvQ2l6suNpZUO1bgYS
